### ISSUE TITLE
FileView rewrite task list

### ISSUE THREAD

**Issue by warpdesign** [warpdesign/react-explorer#343]
- [x] bug: shift + arrow up
- [x] add new useAccelerator hook to replace withAccelerator 
- [x] select all implementation
- [x] handle right click
- [x] double click implementation
- [x] enter to open a file implementation
- [x] alert on double click errors with user friendly messages
- [x] header display
- [x] header click = update sort method
- [x] drag & drop
- [x] drag & drop: preview
- [x] inline edit implementation
- [x] inline edit: what happens when changing tab & going back to previous tab which was editing
- [x] inline edit: what happens if cache is refreshed while editing a file that was removed/renamed
- [x] invert selection implementation
