### ISSUE TITLE
3.0.0.beta-2 bug list

### ISSUE THREAD

**Issue by warpdesign** [warpdesign/react-explorer#351]
- [x] double clicking on a selected file will first activate the inline edit then attempt to open the file #355
- [x] double clicking to open file doesn't seem to work on WSL files (Windows) #352
- [x] changing directory doesn't seem to reset scroll position to top #353
- [x] text-overflow ellipsis is missing in name column (regression) #356
