### ISSUE TITLE
FsZip: checklist

### ISSUE THREAD

**Issue by warpdesign** [warpdesign/react-explorer#392]
- [ ] need to add readonly + checks on Fs so that read+delete+paste+rename operations are disabled
- [ ] need to allow browsing into a dir inside the zip 
- [ ] need to allow browsing a zip by double-clicking in it 
- [ ] need to handle opening a file from zip (by extracking the file in /tmp)
- [ ] need to handle copying files from zip

**Comment by warpdesign** [comment]
Experiment with `archive-files`: it seems to support a wide range of archives and has stream support.

- [ ] list entries (per dir or all entries?)
- [ ] test stream
